language: node_js
# nodejs的版本
node_js:
- "8"  
# 设置自动化部署的源码分支
branches:
  only:
  - dev  
  
# 下面是你的Token加密信息，不要替换
env:
  global:
    secure: dEGwdz5L/8nLJbEYq4OLA0RD1gNfS9XhsPkVdT4nKUMaABSHX5w65x1H7bc4M+dGtJE2r4NGRPO8h3KntXQwrPjMkUNJEOn3YMc9QRr+sgQ/EjRhYqNj4t8KxSmQx6/0HZIuCWk00TBO7YAMibINuSQ7Om9fekqChc8F9ezp87iNyg6lmatMt7XdVGAErImEmRpvMxDMX//4V5V50IdLP+sQ+Wve05JG7r1N2Dwk+Mr6kkEN0lDiqj+20hCd7VaGxRRSy5tJ50pMvsGLs+6wGKfZs3cFwmGO5MqYUnzj1f8IvH1cIWw3+QYwxDiqgE4VgSNAxM9sg3prvDxKM9hbIBBpVRbke0uz42FCjlKpSSPjK5NKB7RsJrEcdNPKoM4OWTX6UYjJDipb83XUDHoSjYR/ZutcG8HAXW+Ov4zdOuQl+fFbEm9JkQnkOAgWvjIBPJU74yZj6dpJ8AamyFaEOO7NNGhIPLdbFYt1PcJffRJAtqc6Y4PVKqco/dwt4TDeYbLg2GS9VX0HgEKptJz8OynkywwCBsQip2/cAkKwW2pooEwUAAEXJCEqsNvscBBJuSH7IjzGYD0MsA/PP2333AKcYB2BZirOdt0lT8P3MSXxBIIXNaQH+FEpRnrXdAX4VGNmZ7jqrDyQ4fgAtisfWf0PC1oOnpOXLwJKLXC59ok=

before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 
before_script:
# 设置github账户信息
- git config --global user.name "LuckyNum"
- git config --global user.email 571996804@qq.com
# github仓库操作  注意将仓库修改成自己的
- sed -i'' "s~git@github.com:LuckyNum/luckynum.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/LuckyNum/luckynum.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy